set nocompatible

" enable syntax plugins
syntax enable
filetype plugin on

" code folding
set foldmethod=syntax   
set foldnestmax=10
set nofoldenable
set foldlevel=2

" Search into directories
set path+=**

" Display all matching files when tab complete
set wildmenu

" General
set number	" Show line numbers
set nowrap	" Wrap lines
set showbreak=+++	" Wrap-broken line prefix
set textwidth=100	" Line wrap (number of cols)
set showmatch	" Highlight matching brace
"set spell	" Enable spell-checking
set visualbell	" Use visual bell (no beeping)
 
set hlsearch	" Highlight all search results
set smartcase	" Enable smart-case search
set gdefault	" Always substitute all matches in a line
set ignorecase	" Always case-insensitive
set incsearch	" Searches for strings incrementally
 
set autoindent	" Auto-indent new lines
set expandtab	" Use spaces instead of tabs
set shiftwidth=4	" Number of auto-indent spaces
set smartindent	" Enable smart-indent
set smarttab	" Enable smart-tabs
set softtabstop=4	" Number of spaces per Tab
 
" Advanced
set ruler	" Show row and column ruler information
set showtabline=2	" Show tab bar
 
set undolevels=1000	" Number of undo levels
set backspace=indent,eol,start	" Backspace behaviour
 
 
"" Generated by VimConfig.com
